### ISSUE TITLE
Fail to install sonar-scala on SonarQube 8.7

### ISSUE THREAD

**Issue by evasokolova1f** [sonar-scala/sonar-scala#791]
Hi!

I try to install sonar-scala plugin on SonarQube 8.7.
So I download jar file from https://s01.oss.sonatype.org/content/repositories/releases/com/sonar-scala/sonar-scala_2.13/8.7.0/sonar-scala_2.13-8.7.0-assembly.jar, saved it in /opt/sonarqube/extensions/plugins directory.
But after server restart I have such error in web.log:
`2021.12.22 16:54:52 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: There are two languages declared with the same key 'scala' declared by the plugins 'scala' and 'sonarscala'. Please uninstall one of the conflicting plugins.
	at org.sonar.server.language.LanguageValidation.lambda$start$1(LanguageValidation.java:48)
	at java.base/java.util.HashMap.merge(HashMap.java:1298)
	at java.base/java.util.stream.Collectors.lambda$toMap$68(Collectors.java:1658)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.sonar.server.language.LanguageValidation.start(LanguageValidation.java:44)
	at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:576)
	at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:213)
	at org.sonar.server.platform.PlatformImpl.startLevel34Containers(PlatformImpl.java:187)
	at org.sonar.server.platform.PlatformImpl.access$500(PlatformImpl.java:46)
	at org.sonar.server.platform.PlatformImpl$1.lambda$doRun$0(PlatformImpl.java:120)
	at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:370)
	at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:120)
	at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:354)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021.12.22 16:54:52 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process`

Could you help me, please?

**Comment by mwz** [comment]
You can only have a single plugin for any given language, so you need to remove the sonarsource sonarscala plugin from `/opt/sonarqube/lib/extensions/` in order to be able to use sonar-scala.

See an example from my docker image [here](https://github.com/sonar-scala/sonar-scala-docker/blob/v5.7.0/current/full/Dockerfile#L7).

**Comment by evasokolova1f** [comment]
@mwz Thank you very much!
